version: '3.8'

services:
  db:
    container_name: postgres-migration
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    #volumes:
    #  - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

# docker-compose up -d
# docker-compose up --build   # Это строка выполнения при самом первом запуске "docker-compose.yaml"

# А в контейнере из Docker-desktop в Терминале подключение к созданной в docker-compose БАЗЕ db_migration: 
#                                                                            psql -U root -d db_migration
